# This site is based on the Ananke theme. The Ananke theme documentation:
# https://github.com/theNewDynamic/gohugo-theme-ananke/tree/master
baseURL = "https://kamigonaughtyboys.web.fc2.com"
languageCode = "ja"
title = "上郷ノーティボーイズ"

DefaultContentLanguage = "ja"
Paginate = 20
SectionPagesMenu = "main"
enableRobotsTXT = true
googleAnalytics = ""

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[params]
description = "The last theme you'll ever need. Maybe."
facebook = ""
favicon = ""
github = ""
gitlab = ""
instagram = ""
linkedin = ""
mastodon = ""
rss = ""
site_logo = ""
slack = ""
stackoverflow = ""
twitter = ""
youtube = ""
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
custom_css = ["css/custom.css"]
featured_image = "/images/gohugo-default-sample-hero-image.jpg"
recent_posts_number = 5
body_classes = ""

[markup.goldmark.renderer]
unsafe = true
