# baseURL = "https://kamigonaughtyboys.web.fc2.com"
baseURL = "https://kamigonaughtyboys.netlify.app"
title = "上郷ノーティボーイズ"

# This site is based on the Ananke theme. The Ananke theme documentation:
# https://github.com/theNewDynamic/gohugo-theme-ananke/tree/master
theme = "ananke"

languageCode = "ja"
DefaultContentLanguage = "ja"
Paginate = 20
SectionPagesMenu = "main"
enableRobotsTXT = true
googleAnalytics = ""

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[params]
description = "愛知県豊田市南部にある少年軟式野球チーム・上郷ノーティボーイズです。"
facebook = ""
favicon = ""
instagram = ""
linkedin = ""
rss = ""
site_logo = ""
slack = ""
twitter = ""
youtube = ""
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
custom_css = ["css/custom.css"]
featured_image = ""
recent_posts_number = 5
body_classes = ""
# Specify sections to pull recent posts from.
mainSections = ["articles"]
cover_dimming_class = "bg-black-30"

[markup.goldmark.renderer]
# This is a workdown so that we can embed HTML tags in a markdown file.
# https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032
unsafe = true
